import streamlit as st
import pandas as pd
from openrouteservice import isochrones, client
from datetime import timedelta
import geopandas as gpd
from shapely.geometry import shape, Point
import pydeck as pdk
import json


# TODO:
# move the controls into a side panel; make map full width
# look into autofill for addresses to remove need for validation
# fix the map tooltips so that the intersection is on top; maybe no tooltips because mobile
# de-emphasize the the lines of the isochrones
# add a legend for the isochrones
# (idea): add the intersection ceontroid as a marker
# (idea): add places based on distance from intersection centroid
# (idea): compute directions to places from each location
st.title("Meet Halfway?")

ORS_API_KEY = st.secrets["ORS_API_KEY"]
ORS_PROFILES = ["driving-car", "cycling-regular", "foot-walking"]

retro_metro_palette = [
    "#ea5545",
    "#f46a9b",
    "#ef9b20",
    "#edbf33",
    "#ede15b",
    "#bdcf32",
    "#87bc45",
    "#27aeef",
    "#b33dc6",
]
tab10_palette = [
    "#1f77b4",  # tab:blue
    "#ff7f0e",  # tab:orange
    "#2ca02c",  # tab:green
    "#d62728",  # tab:red
    "#9467bd",  # tab:purple
    "#8c564b",  # tab:brown
    "#e377c2",  # tab:pink
    "#7f7f7f",  # tab:gray
    "#bcbd22",  # tab:olive
    "#17becf",  # tab:cyan
]

COLOR_PALETTE = tab10_palette


# Function to convert hex to RGB
def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip("#")
    return [int(hex_color[i : i + 2], 16) for i in (0, 2, 4)]


# Convert palette to RGB
rgb_colors = [hex_to_rgb(color) for color in COLOR_PALETTE]


def get_ors_client():
    return client.Client(key=ORS_API_KEY)


@st.cache_data
def get_isochrones(
    lonlats: list[tuple[float, float]],
    profile: str,
    max_travel_time_s: int,
    interval: int,
) -> dict:
    """
    Generate isochrones for given locations and travel profile.

    Parameters:
    lonlats (list of tuples): List of (longitude, latitude) pairs representing locations.
    profile (str): Travel profile (e.g., 'driving-car', 'cycling', etc.).
    max_travel_time_s (int): Maximum travel time in seconds (must be > 0 and <= 3600).
    interval (int): Interval in seconds for isochrone generation (must be > 0).

    Returns:
    dict: Isochrones data generated by the ORS client.

    Raises:
    AssertionError: If profile is not in ORS_PROFILES, or if interval or max_travel_time_s are out of valid range.
    """
    assert profile in ORS_PROFILES
    assert interval > 0
    assert (
        max_travel_time_s > 0
        and max_travel_time_s <= timedelta(minutes=30).total_seconds()
    )
    return isochrones.isochrones(
        client=get_ors_client(),
        locations=lonlats,
        profile=profile,
        range=[max_travel_time_s],
        interval=interval,
        range_type="time",
    )


### get the locations
# get input from the user for the locations (at least two required)
# we'll show the user a button to add more locations, and a field that allows them to input the address
# we'll use the geocode function to get the coordinates for the address
# we'll store the locations in a geopandas dataframe, with a a layer value indicating these are markers


@st.cache_data
def geocode_address(address):
    ors_client = get_ors_client()
    geocode_result = ors_client.pelias_search(text=address)
    if geocode_result and geocode_result["features"]:
        coordinates = geocode_result["features"][0]["geometry"]["coordinates"]
        return coordinates[0], coordinates[1]
    else:
        st.error(f"Address '{address}' could not be geocoded.")
        return None


locations = []

st.header("Where is everyone coming from:")
address_inputs = [
    st.text_input("Address 1", placeholder="123 Main St, City, State"),
    st.text_input("Address 2", placeholder="456 Elm St, City, State"),
]

with st.expander("Add more addresses"):
    for i in range(3, 6):
        address_inputs.append(
            st.text_input(f"Address {i}", placeholder=f"789 Oak St, City, State")
        )

for address in address_inputs:
    if address:
        coord = geocode_address(address)
        if coord:
            locations.append({"address": address, "lat": coord[1], "lon": coord[0]})

coordinates = [(loc["lon"], loc["lat"]) for loc in locations]

if len(coordinates) < 2:
    st.warning("Please enter at least two valid addresses.")


### start mapping the points
# this will be so that users get quick feedback that their locations are correct
# each will be assigned a color, which we'll store in the dataframe

else:
    # st.success("Addresses geocoded successfully.")
    locations_df = pd.DataFrame(locations)
    locations_df["layer"] = "markers"

    # pick colors determinstically for each location, based on their index
    locations_df["color"] = [
        rgb_colors[i % len(rgb_colors)] for i in range(len(locations_df))
    ]
    # st.map(locations_df)
    # st.write(locations_df)

### get the isochrone parameters

# we'll show the user a dropdown to select the travel profile
profile = st.selectbox("How do we get there?", ORS_PROFILES)

# we'll show the user a slider to select the maximum travel time, maximum of 30 minutes, intervals of 5 minutes

# max_travel_time_minutes = st.number_input(
#     "How far is everyone willing to travel? (minutes)",
#     min_value=10,
#     max_value=30,
#     value=30,
#     step=5,
# )

max_travel_time_minutes = 30

# convert to seconds with datetime
max_travel_time_s = timedelta(minutes=max_travel_time_minutes).total_seconds()

# intervals will be set such that there are 5 isochrones generated (e.g. at 5, 10, 20, 25, 30 minutes)
# for iteration, we can make the number of isochrones a parameter that the user can set, up to 10

# n_intervals = st.number_input(
#     "Number of Isochrones",
#     min_value=1,
#     max_value=10,
#     value=5,
#     step=1,
# )

n_intervals = 10

interval = max_travel_time_s / n_intervals


### Compute the isochrones
resp = get_isochrones(
    lonlats=coordinates,
    profile=profile,
    max_travel_time_s=max_travel_time_s,
    interval=interval,
)

# Derive the center_lat and center_lon from the bounding box
bbox = resp["bbox"]
center_lat = (bbox[1] + bbox[3]) / 2
center_lon = (bbox[0] + bbox[2]) / 2

# Store the isochrones in a GeoDataFrame with Shapely geometries
isochrones_dict_list = []
for i, feature in enumerate(resp["features"]):
    # Convert GeoJSON geometry to Shapely geometry
    geometry = shape(feature["geometry"])
    isochrones_dict_list.append(
        {
            "geometry": geometry,
            "travel_time_s": feature["properties"]["value"],
            "layer": "isochrones",
            "center_lat": feature["properties"]["center"][1],
            "center_lon": feature["properties"]["center"][0],
        }
    )

# Create GeoDataFrame with the converted geometries
isochrones_gdf = gpd.GeoDataFrame(
    isochrones_dict_list, geometry="geometry", crs="EPSG:4326"
)

# Merge with locations_df using rounded coordinates
rounding_precision = 2
isochrones_gdf["lat_rounded"] = isochrones_gdf["center_lat"].round(rounding_precision)
isochrones_gdf["lon_rounded"] = isochrones_gdf["center_lon"].round(rounding_precision)
locations_df["lat_rounded"] = locations_df["lat"].round(rounding_precision)
locations_df["lon_rounded"] = locations_df["lon"].round(rounding_precision)

isochrones_gdf = isochrones_gdf.merge(
    locations_df[["address", "color", "lat_rounded", "lon_rounded"]],
    on=["lat_rounded", "lon_rounded"],
    how="left",
).drop(columns=["lat_rounded", "lon_rounded"])

# set the isochrone fill and line colors
isochrones_gdf["fill_color"] = isochrones_gdf["color"].apply(lambda c: c + [20])
isochrones_gdf["line_color"] = isochrones_gdf["color"].apply(lambda c: c + [255])


# st.write(isochrones_gdf)

# Compute the intersection of the isochrones with the same time
intersection_centroid = None
intersections = []
for time, group in isochrones_gdf.groupby("travel_time_s"):
    if len(group) > 1:
        intersection = gpd.GeoDataFrame(
            group.iloc[0:1], geometry="geometry", crs="EPSG:4326"
        )
        for i in range(1, len(group)):
            next_isochrone = gpd.GeoDataFrame(
                group.iloc[i : i + 1], geometry="geometry", crs="EPSG:4326"
            )
            try:
                intersection = gpd.overlay(
                    intersection, next_isochrone, how="intersection"
                )
                if intersection.empty:
                    break
            except Exception as e:
                st.warning(f"No intersection found for travel time {time} seconds: {e}")
                break
        if not intersection.empty:
            intersection["layer"] = "intersections"
            intersection["travel_time_s"] = time
            intersections.append(intersection)

if intersections:
    intersections_gdf = gpd.GeoDataFrame(
        pd.concat(intersections, ignore_index=True), crs="EPSG:4326"
    )
    # set the intersection colors to white with 50% opacity as an array
    intersections_gdf["color"] = [[255, 255, 255]] * len(intersections_gdf)
    intersections_gdf["address"] = "Intersection"
    # trim to just columns that are relevant
    intersections_gdf = intersections_gdf[
        ["geometry", "travel_time_s", "layer", "color", "address"]
    ]
    # st.write(intersections_gdf)
else:
    st.info("No intersections found.")
# the layer for the intersections will be labeled as such

### user will select the specific isochrones they want to use with a slider
# this will be default to the lowest isochrone that has an intersection, but will range from the lowest to the highest isochrone

# get the lowest isochrone that has an intersection
lowest_isochrone_with_intersection = (
    intersections_gdf["travel_time_s"].min() if intersections else None
)
times = isochrones_gdf["travel_time_s"].unique()
times.sort()

# st.write("Select the isochrone to use:")
selected_isochrone = st.select_slider(
    "Travel time (minutes)",
    options=[int(t / 60) for t in times],
    value=(
        int(lowest_isochrone_with_intersection / 60)
        if lowest_isochrone_with_intersection
        else int(times[0] / 60)
    ),
)

# filter the isochrones and intersections to the selected one
selected_isochrone_s = selected_isochrone * 60
selected_isochrone_gdf = isochrones_gdf[
    isochrones_gdf["travel_time_s"] == selected_isochrone_s
]
selected_intersections_gdf = intersections_gdf[
    intersections_gdf["travel_time_s"] == selected_isochrone_s
]

# convert to GeoJSON for display
selected_isochrone_json_dict = json.loads(selected_isochrone_gdf.to_json())
selected_intersections_json_dict = json.loads(selected_intersections_gdf.to_json())

# show these as tables if the show raw data checkbox is selected
if st.checkbox("Show Raw Data"):
    st.text("Geodataframe for selected isochrone:")
    st.write(selected_isochrone_gdf)
    st.write(selected_intersections_gdf)
    st.text("GeoJSON for selected isochrone:")
    st.write(selected_isochrone_json_dict)
    st.write(selected_intersections_json_dict)


### show the map
# we'll show the map with the locations, isochrones, and intersections using pydeck

# Prepare data for ScatterplotLayer by creating a position column
locations_df["position"] = locations_df.apply(
    lambda row: [row["lon"], row["lat"]], axis=1
)

# Define layers
isochrone_layer = pdk.Layer(
    "GeoJsonLayer",
    id="Isochrones",
    data=selected_isochrone_json_dict,
    filled=True,
    get_fill_color="properties.fill_color",
    stroked=True,
    get_line_color="properties.line_color",
    get_line_width=200,
    pickable=True,
    # auto_highlight=True,
)

intersection_layer = pdk.Layer(
    "GeoJsonLayer",
    id="Intersections",
    data=selected_intersections_json_dict,
    filled=True,
    get_fill_color=[255, 255, 255, 150],
    stroked=False,
    pickable=True,
    # auto_highlight=True,
)

marker_layer = pdk.Layer(
    "ScatterplotLayer",
    id="Markers",
    data=locations_df,
    get_position="position",
    get_radius=500,
    get_fill_color="color",
    pickable=True,
)

# Combine all geometries to calculate the total bounds
all_geometries = pd.concat(
    [
        selected_isochrone_gdf["geometry"],
        selected_intersections_gdf["geometry"],
        locations_df.apply(lambda row: Point(row["lon"], row["lat"]), axis=1),
    ],
    ignore_index=True,
)

# pick a centroid for the map view
if len(selected_intersections_gdf) > 0:
    centroid = selected_intersections_gdf.geometry.unary_union.centroid
    centroid_marker_layer = pdk.Layer(
        "ScatterplotLayer",
        id="CentroidMarker",
        data=pd.DataFrame([{"position": [centroid.x, centroid.y]}]),
        get_position="position",
        get_radius=700,
        get_fill_color=[255, 255, 255, 200],
        pickable=True,
    )
else:
    gdf_all = gpd.GeoDataFrame(geometry=all_geometries, crs="EPSG:4326")
    centroid = gdf_all.geometry.unary_union.centroid
    centroid_marker_layer = None


# Set initial view state
view_state = pdk.ViewState(
    latitude=centroid.y,
    longitude=centroid.x,
    zoom=10,
    pitch=0,
    bearing=0,
)

# Create the deck
deck = pdk.Deck(
    initial_view_state=view_state,
    layers=[
        intersection_layer,
        isochrone_layer,
        marker_layer,
        # centroid_marker_layer,
    ],
    tooltip={
        "html": "<b>{address}</b><br>Travel Time: {travel_time_s} seconds",
    },
)

# Render the map in Streamlit
st.pydeck_chart(deck)

### TODO: search for POIs based on what the user wants to do, i.e. restaurants, parks, etc.
# the user will be able to select the type of POI they want to search for
# we'll use the ORS POI search to get the POIs within the intersection that's selected
# we'll show the POIs on the map

### TODO: get directions to the POIs
# and then we'll compute directions from each location the user entered to each of the POIs returned
# this will will then be overlayed on the map based on which POI is selected, to visualize the routes each person will take
# we'll also show the travel time for each route

### TODO: search for POIs based on what the user wants to do, i.e. restaurants, parks, etc.
# the user will be able to select the type of POI they want to search for
# we'll use the ORS POI search to get the POIs within the intersection that's selected
# we'll show the POIs on the map

### TODO: get directions to the POIs
# and then we'll compute directions from each location the user entered to each of the POIs returned
# this will will then be overlayed on the map based on which POI is selected, to visualize the routes each person will take
# we'll also show the travel time for each route
